version: "3.3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    restart: on-failure
    ports:
      - "80:3000"
    volumes:
      - ./frontend/src:/app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: on-failure
    ports:
      - "8000:8000"
