version: "3.3"
services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: reverse-proxy
    restart: always
  frontend:
    image: kuosandys/cca-sustainability-frontend:latest
    container_name: frontend
    restart: on-failure
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: on-failure
    ports:
      - "8000:8000"
