name: Docker Image CI

on:
  push:
    paths: 'frontend/**'

jobs:

  push_to_dockerhub:
    name: Build Docker image and push to Dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: Dockerfile
          push: true
          tags: kuosandys/cca-sustainability-frontend:latest
